# Generated by Django 2.2.6 on 2019-10-10 21:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20191010_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 10, 21, 19, 42, 471897, tzinfo=utc)),
        ),
    ]
